package fallofrome.game;

public enum Phase {
    GAMEOVER,
    SETUP,
    INTERNAL_REVOLUTION_PHASE,
    NON_ROMAN_NON_LOYAL_ROMAN_MOVEMENT_PHASE,
    NON_ROMAN_NON_LOYAL_ROMAN_COMBAT_PHASE,
    BARBARIAN_CREATION_PHASE,
    LOYAL_ROMAN_MOVEMENT_PHASE,
    LOYAL_ROMAN_COMBAT_PHASE,
    LEGION_REBELLION_PHASE,
    CONTROL_DETERMINATION_PHASE,
    BARBARIAN_ATTRITION_PHASE,
    TAX_COLLECTION_DISBURSEMENT_PHASE,
    ROMAN_PERSIAN_REPLACEMENT_PHASE,
    BARBARIAN_BRIBE_PHASE,
    GAME_TURN_RECORD_PHASE
}
